// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright (C) 2026 Alexandre Boissiere
// This file is part of the BadLands operating system.
//
// This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, version 3.
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see <https://www.gnu.org/licenses/>. 

#include <stdint.h>

#include <devices/KeyboardDispatcher/Keycodes.h>

const uint8_t KeyboardDispatcher_KeycodeMap[8 * 20] = {
    [KEYPOINT(0,  0)] = VK_INVALID,
    [KEYPOINT(0,  1)] = VK_INVALID,
    [KEYPOINT(0,  2)] = VK_INVALID,
    [KEYPOINT(0,  3)] = VK_INVALID,
    [KEYPOINT(0,  4)] = VK_INVALID,
    [KEYPOINT(0,  5)] = VK_INVALID,
    [KEYPOINT(0,  6)] = VK_INVALID,
    [KEYPOINT(0,  7)] = VK_INVALID,
    [KEYPOINT(0,  8)] = VK_INVALID,
    [KEYPOINT(0,  9)] = VK_INVALID,
    [KEYPOINT(0, 10)] = VK_BROWSER_HOME,
    [KEYPOINT(0, 11)] = VK_BROWSER_SEARCH,
    [KEYPOINT(0, 12)] = VK_BROWSER_FAVORITES,
    [KEYPOINT(0, 13)] = VK_BROWSER_REFRESH,
    [KEYPOINT(0, 14)] = VK_BROWSER_STOP,
    [KEYPOINT(0, 15)] = VK_BROWSER_FORWARD,
    [KEYPOINT(0, 16)] = VK_BROWSER_BACK,
    [KEYPOINT(0, 17)] = VK_LAUNCH_APP1,
    [KEYPOINT(0, 18)] = VK_LAUNCH_MAIL,
    [KEYPOINT(0, 19)] = VK_LAUNCH_MEDIA_SELECT,
    [KEYPOINT(1,  0)] = VK_INVALID,
    [KEYPOINT(1,  1)] = VK_F13,
    [KEYPOINT(1,  2)] = VK_F14,
    [KEYPOINT(1,  3)] = VK_F15,
    [KEYPOINT(1,  4)] = VK_F16,
    [KEYPOINT(1,  5)] = VK_F17,
    [KEYPOINT(1,  6)] = VK_F18,
    [KEYPOINT(1,  7)] = VK_F19,
    [KEYPOINT(1,  8)] = VK_F20,
    [KEYPOINT(1,  9)] = VK_F21,
    [KEYPOINT(1, 10)] = VK_F22,
    [KEYPOINT(1, 11)] = VK_F23,
    [KEYPOINT(1, 12)] = VK_F24,
    [KEYPOINT(1, 13)] = VK_SNAPSHOT,
    [KEYPOINT(1, 14)] = VK_SCROLL,
    [KEYPOINT(1, 15)] = VK_PAUSE,
    [KEYPOINT(1, 16)] = VK_VOLUME_MUTE,
    [KEYPOINT(1, 17)] = VK_VOLUME_DOWN,
    [KEYPOINT(1, 18)] = VK_VOLUME_UP,
    [KEYPOINT(1, 19)] = VK_LAUNCH_APP2,
    [KEYPOINT(2,  0)] = VK_ESCAPE,
    [KEYPOINT(2,  1)] = VK_F1,
    [KEYPOINT(2,  2)] = VK_F2,
    [KEYPOINT(2,  3)] = VK_F3,
    [KEYPOINT(2,  4)] = VK_F4,
    [KEYPOINT(2,  5)] = VK_F5,
    [KEYPOINT(2,  6)] = VK_F6,
    [KEYPOINT(2,  7)] = VK_F7,
    [KEYPOINT(2,  8)] = VK_F8,
    [KEYPOINT(2,  9)] = VK_F9,
    [KEYPOINT(2, 10)] = VK_F10,
    [KEYPOINT(2, 11)] = VK_F11,
    [KEYPOINT(2, 12)] = VK_F12,
    [KEYPOINT(2, 13)] = VK_INSERT,
    [KEYPOINT(2, 14)] = VK_HOME,
    [KEYPOINT(2, 15)] = VK_PRIOR,
    [KEYPOINT(2, 16)] = VK_MEDIA_STOP,
    [KEYPOINT(2, 17)] = VK_MEDIA_PREV_TRACK,
    [KEYPOINT(2, 18)] = VK_MEDIA_PLAY_PAUSE,
    [KEYPOINT(2, 19)] = VK_MEDIA_NEXT_TRACK,
    [KEYPOINT(3,  0)] = VK_OEM_3,
    [KEYPOINT(3,  1)] = VK_1,
    [KEYPOINT(3,  2)] = VK_2,
    [KEYPOINT(3,  3)] = VK_3,
    [KEYPOINT(3,  4)] = VK_4,
    [KEYPOINT(3,  5)] = VK_5,
    [KEYPOINT(3,  6)] = VK_6,
    [KEYPOINT(3,  7)] = VK_7,
    [KEYPOINT(3,  8)] = VK_8,
    [KEYPOINT(3,  9)] = VK_9,
    [KEYPOINT(3, 10)] = VK_0,
    [KEYPOINT(3, 11)] = VK_OEM_MINUS,
    [KEYPOINT(3, 12)] = VK_OEM_PLUS,
    [KEYPOINT(3, 13)] = VK_BACK,
    [KEYPOINT(3, 14)] = VK_DELETE,
    [KEYPOINT(3, 15)] = VK_END,
    [KEYPOINT(3, 16)] = VK_NUMLOCK,
    [KEYPOINT(3, 17)] = VK_DIVIDE,
    [KEYPOINT(3, 18)] = VK_MULTIPLY,
    [KEYPOINT(3, 19)] = VK_SUBTRACT,
    [KEYPOINT(4,  0)] = VK_TAB,
    [KEYPOINT(4,  1)] = VK_Q,
    [KEYPOINT(4,  2)] = VK_W,
    [KEYPOINT(4,  3)] = VK_E,
    [KEYPOINT(4,  4)] = VK_R,
    [KEYPOINT(4,  5)] = VK_T,
    [KEYPOINT(4,  6)] = VK_Y,
    [KEYPOINT(4,  7)] = VK_U,
    [KEYPOINT(4,  8)] = VK_I,
    [KEYPOINT(4,  9)] = VK_O,
    [KEYPOINT(4, 10)] = VK_P,
    [KEYPOINT(4, 11)] = VK_OEM_4,
    [KEYPOINT(4, 12)] = VK_OEM_6,
    [KEYPOINT(4, 13)] = VK_OEM_5,
    [KEYPOINT(4, 14)] = VK_NEXT,
    [KEYPOINT(4, 15)] = VK_INVALID,
    [KEYPOINT(4, 16)] = VK_NUMPAD7,
    [KEYPOINT(4, 17)] = VK_NUMPAD8,
    [KEYPOINT(4, 18)] = VK_NUMPAD9,
    [KEYPOINT(4, 19)] = VK_INVALID,
    [KEYPOINT(5,  0)] = VK_CAPITAL,
    [KEYPOINT(5,  1)] = VK_A,
    [KEYPOINT(5,  2)] = VK_S,
    [KEYPOINT(5,  3)] = VK_D,
    [KEYPOINT(5,  4)] = VK_F,
    [KEYPOINT(5,  5)] = VK_G,
    [KEYPOINT(5,  6)] = VK_H,
    [KEYPOINT(5,  7)] = VK_J,
    [KEYPOINT(5,  8)] = VK_K,
    [KEYPOINT(5,  9)] = VK_L,
    [KEYPOINT(5, 10)] = VK_OEM_1,
    [KEYPOINT(5, 11)] = VK_OEM_7,
    [KEYPOINT(5, 12)] = VK_INVALID,
    [KEYPOINT(5, 13)] = VK_RETURN,
    [KEYPOINT(5, 14)] = VK_INVALID,
    [KEYPOINT(5, 15)] = VK_INVALID,
    [KEYPOINT(5, 16)] = VK_NUMPAD4,
    [KEYPOINT(5, 17)] = VK_NUMPAD5,
    [KEYPOINT(5, 18)] = VK_NUMPAD6,
    [KEYPOINT(5, 19)] = VK_ADD,
    [KEYPOINT(6,  0)] = VK_LSHIFT,
    [KEYPOINT(6,  1)] = VK_OEM_102,
    [KEYPOINT(6,  2)] = VK_Z,
    [KEYPOINT(6,  3)] = VK_X,
    [KEYPOINT(6,  4)] = VK_C,
    [KEYPOINT(6,  5)] = VK_V,
    [KEYPOINT(6,  6)] = VK_B,
    [KEYPOINT(6,  7)] = VK_N,
    [KEYPOINT(6,  8)] = VK_M,
    [KEYPOINT(6,  9)] = VK_OEM_COMMA,
    [KEYPOINT(6, 10)] = VK_OEM_PERIOD,
    [KEYPOINT(6, 11)] = VK_OEM_2,
    [KEYPOINT(6, 12)] = VK_RSHIFT,
    [KEYPOINT(6, 13)] = VK_UP,
    [KEYPOINT(6, 14)] = VK_INVALID,
    [KEYPOINT(6, 15)] = VK_INVALID,
    [KEYPOINT(6, 16)] = VK_NUMPAD1,
    [KEYPOINT(6, 17)] = VK_NUMPAD2,
    [KEYPOINT(6, 18)] = VK_NUMPAD3,
    [KEYPOINT(6, 19)] = VK_SEPARATOR,
    [KEYPOINT(7,  0)] = VK_LCONTROL,
    [KEYPOINT(7,  1)] = VK_LWIN,
    [KEYPOINT(7,  2)] = VK_LMENU,
    [KEYPOINT(7,  3)] = VK_INVALID,
    [KEYPOINT(7,  4)] = VK_INVALID,
    [KEYPOINT(7,  5)] = VK_INVALID,
    [KEYPOINT(7,  6)] = VK_SPACE,
    [KEYPOINT(7,  7)] = VK_INVALID,
    [KEYPOINT(7,  8)] = VK_RMENU,
    [KEYPOINT(7,  9)] = VK_RWIN,
    [KEYPOINT(7, 10)] = VK_APPS,
    [KEYPOINT(7, 11)] = VK_RCONTROL,
    [KEYPOINT(7, 12)] = VK_LEFT,
    [KEYPOINT(7, 13)] = VK_DOWN,
    [KEYPOINT(7, 14)] = VK_RIGHT,
    [KEYPOINT(7, 15)] = VK_INVALID,
    [KEYPOINT(7, 16)] = VK_NUMPAD0,
    [KEYPOINT(7, 17)] = VK_INVALID,
    [KEYPOINT(7, 18)] = VK_DECIMAL,
    [KEYPOINT(7, 19)] = VK_RETURN
};
